import type { Metadata } from "next";
import dynamic from "next/dynamic";
import path from "path";
import { promises as fs } from "fs";

import "./globals.css";
import { tajawal } from "./fonts";
import sortByDate from "@/utils/sortByDate";

const ClientLayout = dynamic(() => import("@/components/ClientLayout"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "TV App",
  description: "Generated by create next app for VECTO.DIGITAL",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const filePath = path.join(process.cwd(), "public", "data.json");
  const fileContents = await fs.readFile(filePath, "utf8");

  const { Featured, TrendingNow } = JSON.parse(fileContents);

  return (
    <html lang="en">
      <body className={`${tajawal.className} bg-black`}>
        <ClientLayout Featured={Featured} TrendingNow={sortByDate(TrendingNow)}>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
};

export default RootLayout;
